# SPDX-License-Identifier: GPL-2.0

#
# This file is part of Lustre, http://www.lustre.org/
#
# Makefile.in
#
# Template to generate top-level Makefile
#

obj-m += / libcfs/ lnet/
obj-m += lustre/

include /root/lustre-Eurosys26/existing/lustre-existing/Rules
