MODULES := mgc
mgc-objs := mgc_request.o lproc_mgc.o
#mgc-objs += mgc_request_server.o

EXTRA_DIST := $(mgc-objs:%.o=%.c) mgc_internal.h mgc_request_server.c

include /root/lustre-Eurosys26/existing/lustre-existing/Rules
