MODULES = osp
osp-objs = osp_dev.o osp_object.o osp_precreate.o osp_sync.o lproc_osp.o
osp-objs += lwp_dev.o osp_md_object.o osp_trans.o

EXTRA_DIST = $(osp-objs:.o=.c) osp_internal.h

include /root/lustre-Eurosys26/existing/lustre-existing/Rules
